name: Semgrep
description: Must run under ubuntu

inputs:
  rules:
    description: Rules
    default: p/default
    required: true
  timeout:
    description: Timeout default 1800 seconds (30 minutes). Set to 0 to disable.
    default: '1800'
    required: true
  
runs:
  using: composite

  steps:
    - uses: actions/checkout@v3

    # - name: Setup homebrew
    #   uses: Homebrew/actions/setup-homebrew@master

    # - run: brew install cyclonedx/cyclonedx/cyclonedx-cli

    - name: Install semgrep
      run: python3 -m pip install semgrep
      shell: bash

    - name: Run semgrep
      env:
        Rules: ${{ github.event.inputs.rules }}
        Timeout: ${{ github.event.inputs.timeout }}
      run: semgrep ci -c p/default
      shell: bash
