name: Semgrep
description: Must run under ubuntu

inputs:
  rules:
    description: Rules
    default: p/default
    required: true
  timeout:
    description: Timeout default 1800 seconds (30 minutes). Set to 0 to disable.
    default: '1800'
    required: true
  
runs:
  using: composite

  steps:
    - uses: actions/checkout@v3
      with: 
        repository: sbaker-devolutions/actions
        ref: master
        path: actionrepo

    - run: ls -LR
      shell: bash

    # - name: Setup homebrew
    #   uses: Homebrew/actions/setup-homebrew@master

    # - run: brew install cyclonedx/cyclonedx/cyclonedx-cli

    - run: python3 -m pip install semgrep
      shell: bash

      # -o semgrep_result.txt --suppress-errors 
    - run: semgrep ci -c actionrepo/semgrep/$rules --timeout $timeout
      env:
        rules: ${{ inputs.rules }}
        timeout: ${{ inputs.timeout }}
      shell: bash

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: semgrep_result.txt
    #     path: semgrep_result.txt
