name: Semgrep

inputs:
  rules:
    description: Rules
    default: p/default
    required: true
  timeout:
    description: Timeout default 1800 seconds (30 minutes). Set to 0 to disable.
    default: '1800'
    required: true
  
runs:
  using: composite

  steps:
    - name: verify semgrep compatibility
      if: ${{ runner.os != 'Linux' }}
      uses: actions/github-script@v3
      with:
        script: core.setFailed('Semgrep action must run under Ubuntu!')

    - name: checkout semgrep rules 
      uses: actions/checkout@v3
      with: 
        repository: sbaker-devolutions/semgrep-rules
        ref: master
        path: rules

    - name: install semgrep
      run: python3 -m pip install semgrep
      shell: bash

    - name: run semgrep
      run: semgrep ci -c $rules --timeout $timeout -o semgrep_result.txt
      shell: bash
      env:
        rules: ${{ inputs.rules }}
        timeout: ${{ inputs.timeout }}

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: semgrep_result.txt
        path: semgrep_result.txt
        if-no-files-found: ignore
