name: Semgrep

inputs:
  rules:
    description: Rules
    default: p/default
    required: true
  timeout:
    description: Timeout default 1800 seconds (30 minutes). Set to 0 to disable.
    default: '1800'
    required: true
  
runs:
  using: composite

  steps:
    - uses: actions/github-script@v3
      if: ${{ runner.os != 'Linux' }}
      with:
        script: core.setFailed('Semgrep action must run under Ubuntu!')

    - uses: actions/checkout@v3
      with: 
        repository: sbaker-devolutions/semgrep-rules
        ref: master
        path: rules

    - run: python3 -m pip install semgrep
      shell: bash

    - run: semgrep ci -c $rules --timeout $timeout -o semgrep_result.txt || true
      env:
        rules: ${{ inputs.rules }}
        timeout: ${{ inputs.timeout }}
      shell: bash

    - run: $env:SEMGREP_FILE_EXISTS = Test-Path semgrep_result.txt -PathType Leaf
      shell: pwsh

    - uses: actions/upload-artifact@v3
      with:
        name: semgrep_result.txt
        path: semgrep_result.txt
        if-no-files-found: ignore
      if: ${{ env.SEMGREP_FILE_EXISTS == 'True' }}
